server:
  port: 8555
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/shop?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' from DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statement: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-propertis: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: 127.0.0.1,192.168.1.*,172.*,61.174.52.*
        deny: 192.168.1.1
        reset-enable: false
        login-username: crawlab_admin
        login-password: 123456
debug:
  true
logging:
  level:
    org.springframework.boot.autoconfigure: info
    com:
      hgk:
        boot:
          mapper: DEBUG